apiVersion: apps/v1
kind: Deployment
metadata:
  name: stakater-backend
  namespace: stakater
  labels:
    app: stakater-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stakater-backend
  template:
    metadata:
      labels:
        app: stakater-backend
    spec:
      containers:
      - name: stakater-backend
        image: stakater-backend
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /sayhello
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: stakater-backend
  name: stakater-backend
  namespace: stakater
spec:
  ports:
  - name: 
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: stakater-backend
  type: ClusterIP
